### ISSUE TITLE
Multi-gpu training support

### ISSUE THREAD

**Issue by devgunn** [neulab/extreme-adaptation-for-personalized-translation#2]
Thanks for sharing your code.
I am wondering if this code supports only single gpu because I see the dynet-gpus(num of gpus) options in options.py, but I don't see any other part related with multi-gpu in other codes.
Moreover, when I start training with 4 GPUS, it allocates 4 GPUS, but uses only 1 GPU.
Hope to hear from you.
Thanks

**Comment by pmichel31415** [comment]
Hi, right now multi-gpu training is not supported and I have no plan to add it in the near future. For the model sizes used in the paper, a single 1080 Ti GPU was enough (memory-wise).

If you're running into out of memory error I suggest decreasing the batch size and maybe add delayed update (eg halve the batch size but call `trainer.update()` every 2 batches)
